services:
  backend:
    build: ./server
    image: scanner-server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    image: scanner-client
    ports:
      - "80:80"
    depends_on:
      - backend